<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ElectricalDesigner.Domain\ElectricalDesigner.Domain.csproj" />
    <ProjectReference Include="..\ElectricalDesigner.Application\ElectricalDesigner.Application.csproj" />
    <ProjectReference Include="..\ElectricalDesigner.Infrastructure\ElectricalDesigner.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
